### ISSUE TITLE
SMS Need to be Toll Free

### ISSUE THREAD

**Issue by JimStuver** [PacoVu/ringcentral-send-tollfree-sms#7] opened 2021-01-06 21:14 UTC
Filled out the form to get a high volume SMS number, but it is NOT TF.  Is that a necessity?  The number was changed and recieved email statung so, but no number appears in the dropdown on the Send Toll Free SMS page.

**Comment by PacoVu** [comment] 2021-03-31 21:01
This is not the technical/programming issue. Please use the Feedback form. But the root cause of this issue is that the provisioned number is not assigned to the user extension you login the app.

**Closed as completed by PacoVu** 2021-03-31 21:01 UTC
